### ISSUE TITLE
How to show specific category products on top while sorting by latest woocommerce?

### ISSUE THREAD

**Issue by sohaibahmed293** [godaddy-wordpress/woocommerce-extra-product-sorting-options#27]
How to show any specific category products on top in the shop catalog page when sorting products by latest in woocommerce wordpress?

For example I've three categories: "Shirts", "Hoodies" & "Jackets".

I would like to show "Shirts" category products on top when shop is sorted by latest. Is this possible ? If yes, then how ?

Thanks

**Comment by unfulvio-godaddy** [comment]
Hi @sohaibahmed293  thanks for reaching out and sorry for the late reply -- I recommend submitting support questions over to [wordpress.org/support/plugin/woocommerce-extra-product-sorting-options](https://wordpress.org/support/plugin/woocommerce-extra-product-sorting-options/) you are more likely to receive a quicker reply there -- thanks
