### ISSUE TITLE
How to Show On Sale Products in Descending Order

### ISSUE THREAD

**Issue by abhinay1435** [godaddy-wordpress/woocommerce-extra-product-sorting-options#28]
Hello,

I want to show Discounted items on Shop Page in Descending Order of their Sale percentage.

For example:
Products with highest percentage should come on top and so on...

**Comment by unfulvio-godaddy** [comment]
Hi @abhinay1435 thanks for reaching out and sorry for the late reply -- I recommend submitting support questions over to https://wordpress.org/support/plugin/woocommerce-extra-product-sorting-options/ you are more likely to receive a quicker reply there -- thanks
